name: Bump and build

on:
 workflow_dispatch:
   inputs:
     bump:
       description: 'Bump rule'
       required: true
       default: prerelease
       type: choice
       options:
       - major
       - minor
       - patch
       - prerelease
       - premajor
       - preminor
       - prepatch

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  version:
    name: 'Determine release version'
    runs-on: ubuntu-20.04

    outputs:
      version: ${{ env.VERSION }}

    steps:
      - name: test
        run: echo "This step will be skipped on Monday and Wednesday"

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get the latest tag
        if: github.event_name == 'workflow_dispatch'
        id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true

      - uses: actions-ecosystem/action-bump-semver@v1
        if: github.event_name == 'workflow_dispatch'
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ github.event.inputs.bump }}

      - name: Set VERSION variable for global release
        if: github.event_name == 'workflow_dispatch'
        run: echo VERSION=${{ steps.bump-semver.outputs.new_version }} >> $GITHUB_ENV

  build_push:
    needs: version
    name: 'Build and Push image to registry'
    runs-on: ubuntu-20.04

    env:
      VERSION: ${{ needs.version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ORG_TOKEN_GHCR }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}